name: inversaapp
description: A new Flutter project.
publish_to: "none" 
version: 3.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.6.2
  # flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  dotted_border: ^2.0.0+3
  inversa_sdk:
    path: ./inversa_sdk
  flutter_riverpod: ^2.3.6
  riverpod_generator: ^2.2.3
    # git:
    #  url: git@github.com:Abubakarshaikh/inversa_sdk.git
    #  ref: main

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  very_good_analysis: ^5.0.0+1



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf


flutter_gen:
  output: lib/src/assets
  line_length: 80

  integrations:
    flutter_svg: true




flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21