// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TW3aH7TElRIvEIQ_RRt70769Y86b9xM',
    appId: '1:52687758327:web:fc7660e94b6677d05d04f2',
    messagingSenderId: '52687758327',
    projectId: 'inversappmx',
    authDomain: 'inversappmx.firebaseapp.com',
    storageBucket: 'inversappmx.appspot.com',
    measurementId: 'G-LPLLPQG1PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6-KmSu60gorTn4tM_2Q9LiB0hWWhVVs',
    appId: '1:52687758327:android:93bee57ad06f054a5d04f2',
    messagingSenderId: '52687758327',
    projectId: 'inversappmx',
    storageBucket: 'inversappmx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyWQG-AEcY6PQ3ChzilrQRjYAFXi7yIs',
    appId: '1:52687758327:ios:f6aa9645ebea6f685d04f2',
    messagingSenderId: '52687758327',
    projectId: 'inversappmx',
    storageBucket: 'inversappmx.appspot.com',
    iosClientId: '52687758327-v2kt24ad84os2h5q3djskqcnccibm7qm.apps.googleusercontent.com',
    iosBundleId: 'com.abubakar.inversaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyWQG-AEcY6PQ3ChzilrQRjYAFXi7yIs',
    appId: '1:52687758327:ios:2528fb3cd837e0955d04f2',
    messagingSenderId: '52687758327',
    projectId: 'inversappmx',
    storageBucket: 'inversappmx.appspot.com',
    iosClientId: '52687758327-6tudi88nm2e80qjcnnqtfvocang6aljd.apps.googleusercontent.com',
    iosBundleId: 'com.abubakar.inversaapp.RunnerTests',
  );
}
