// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_lim1B3vyUoxLs5usgppWHQWVcbXeHQ',
    appId: '1:838768765778:web:146c0bb9b1c8d55f40e88b',
    messagingSenderId: '838768765778',
    projectId: 'flutter-login-app-19fad',
    authDomain: 'flutter-login-app-19fad.firebaseapp.com',
    storageBucket: 'flutter-login-app-19fad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDRdTIYy4xs3HoiKCbByXZLZOnTL31nk',
    appId: '1:838768765778:android:3eb4069f873b570740e88b',
    messagingSenderId: '838768765778',
    projectId: 'flutter-login-app-19fad',
    storageBucket: 'flutter-login-app-19fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsowq3W4ictA8w-NADP0siipJqqDR6Q5o',
    appId: '1:838768765778:ios:93f12fbb109544f440e88b',
    messagingSenderId: '838768765778',
    projectId: 'flutter-login-app-19fad',
    storageBucket: 'flutter-login-app-19fad.appspot.com',
    iosClientId:
        '838768765778-8hg3v08kem3jgq4s1jco5ps1t9okqkdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsowq3W4ictA8w-NADP0siipJqqDR6Q5o',
    appId: '1:838768765778:ios:09128597a75bdeec40e88b',
    messagingSenderId: '838768765778',
    projectId: 'flutter-login-app-19fad',
    storageBucket: 'flutter-login-app-19fad.appspot.com',
    iosClientId:
        '838768765778-uco38fgfkaavgr3umjtukpuf5kbfffl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterlogin.RunnerTests',
  );
}
